source :rubygems

require File.expand_path('../lib/sunspot/version', __FILE__)

gem 'sunspot', Sunspot::VERSION, :path => File.expand_path('..', __FILE__)

group :test do
  gem 'rspec', '~> 1.3'
  #gem 'ruby-debug'
end

#gem 'rsolr', :path => '/Users/ernie/dev/backupify/rsolr'
gem 'rsolr', :git => 'http://github.com/backupify/rsolr.git', :branch => 'use_nokogiri'